# Generated by Django 4.2.27 on 2026-01-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailygrid',
            name='total_possible_players',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
